# Defaults from wheeledlab_envs. Save one calibrated copy per terrain.
params:
  len_f: 0.101
  len_r: 0.101
  mass: 1.09
  inertia: 0.015
  max_steering_angle: 0.5
  C_tire_f: 20.0
  C_tire_r: 20.0
  C_throttle_a: 5.5
  C_rollf: 0.0
  C_drag: 0.0
  wheel_time_constant: 0.05
  min_wheel_velocity: -6.0
  max_wheel_velocity: 6.0
